-- insert into publisher(name) values
-- 	("D&C Media"),
--     ("Kakao"),
--     ("Shueisha"),
--     ("Viz")
-- 	("Kodansha"),
--     ("Азбука")
-- 	("Kadokawa Shoten"),
--     ("Naver"),
--     ("Webtoon")